// Mock Data for Development
import { Campaign, Submission, User, LeaderboardEntry, Lottery, Gesture, Checkpoint } from '../api/types';

export const MOCK_USER: User = {
  id: 'user_1',
  email: 'alex@example.com',
  wallet_address: '0x1234567890abcdef1234567890abcdef12345678',
  tickets: 47,
  referral_code: 'ALEX2025',
  validations_completed: 23,
  accuracy_rate: 0.96,
  diamonds: 12,
  audit_fail_count: 0,
  trusted_network_ids: ['user_2', 'user_3'],
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'campaign_uniserv',
    title: 'Uniserv CMU Cleanup',
    description: 'One-day cleanup at Uniserv CMU Chiang Mai. Before and after photos required (min 1 minute apart). One participation per user.',
    prize_total: 800,
    min_funding_thb: 50,
    requires_face_recognition: false,
    start_date: '2025-01-30',
    end_date: '2025-01-30',
    status: 'active',
    quest_type: 'uniserv_cleanup',
    checkpoints: [
      {
        id: 'checkpoint_uniserv',
        lat: 18.7937682,
        lng: 98.9665553,
        radius: 100,
        name: 'Uniserv CMU Chiang Mai',
      },
    ],
    gestures: [],
    prize_chest: [
      { label: 'Coffee', emoji: '☕' },
      { label: 'Meal at Uniserv Café', emoji: '🍽️' },
      { label: '40 baht', emoji: '💵' },
      { label: 'Bubble tea', emoji: '🧋' },
    ],
    sponsors: [
      { name: 'Uniserv Café', type: 'cafe', maps_url: 'https://www.google.com/maps/search/Uniserv+CMU+Chiang+Mai' },
      { name: 'CMU Sustainability Office', type: 'company' },
    ],
  },
  {
    id: 'campaign_no_burn',
    title: 'No burning',
    description: 'Commit to no burning for 3 months. Submit one photo per day with GPS. Photo + location proof required.',
    prize_total: 500,
    min_funding_thb: 0,
    requires_face_recognition: false,
    start_date: '2025-01-01',
    end_date: '2025-03-31',
    status: 'active',
    quest_type: 'no_burn',
    checkpoints: [
      {
        id: 'checkpoint_no_burn_daily',
        lat: 18.7937682,
        lng: 98.9665553,
        radius: 50,
        name: 'Daily proof (Your own farm only). Within 50 m from the first photo taken',
      },
    ],
    gestures: [],
    prize_chest: [
      { label: 'Snack', emoji: '🍪' },
      { label: 'Smoothie', emoji: '🥤' },
      { label: '50 baht', emoji: '💵' },
    ],
    sponsors: [
      { name: 'Green Farm Co.', type: 'company' },
      { name: 'Mae Ping Organic', type: 'individual' },
    ],
  },
  {
    id: 'campaign_1',
    title: 'Beach Cleanup Challenge',
    description: 'Clean up beaches and earn tickets for the grand prize!',
    prize_total: 1000,
    min_funding_thb: 100,
    requires_face_recognition: true,
    start_date: '2025-01-15',
    end_date: '2025-02-15',
    status: 'active',
    checkpoints: [
      {
        id: 'checkpoint_1',
        lat: 7.8136,
        lng: 98.3006,
        radius: 50,
        name: 'Patong Beach',
      },
      {
        id: 'checkpoint_2',
        lat: 7.8800,
        lng: 98.3000,
        radius: 50,
        name: 'Kata Beach',
      },
    ],
    gestures: [
      {
        id: 'gesture_1',
        date: '2025-01-28',
        gesture_type: 'thumbs_up',
        description: 'Show a thumbs up in your gesture photo',
      },
      {
        id: 'gesture_2',
        date: '2025-01-29',
        gesture_type: 'peace_sign',
        description: 'Show a peace sign in your gesture photo',
      },
    ],
    sponsors: [
      { name: 'Beach Resort Phuket', type: 'company', maps_url: 'https://www.google.com/maps/search/Patong+Beach+Phuket' },
      { name: 'Ocean Café', type: 'cafe', maps_url: 'https://www.google.com/maps/search/Ocean+Cafe+Phuket' },
    ],
  },
  {
    id: 'campaign_ban_plastic',
    title: 'Ban plastic',
    description: 'Everyone in your city shows a photo of them carrying veggies or fruits in a tote-bag or something non-plastic.',
    prize_total: 500,
    min_funding_thb: 0,
    requires_face_recognition: false,
    start_date: '2025-01-01',
    end_date: '2025-12-31',
    status: 'active',
    quest_type: 'ban_plastic',
    checkpoints: [
      {
        id: 'checkpoint_chiang_mai',
        lat: 18.7883,
        lng: 98.9853,
        radius: 20000,
        name: 'Chiang Mai (whole city area)',
      },
    ],
    gestures: [],
    prize_chest: [
      { label: 'Reusable tote', emoji: '🛍️' },
      { label: 'Coffee', emoji: '☕' },
      { label: '50 baht', emoji: '💵' },
    ],
    sponsors: [
      { name: 'Ristr8to', type: 'cafe', maps_url: 'https://www.google.com/maps/search/Ristr8to+Chiang+Mai' },
      { name: 'Chiang Mai Green Initiative', type: 'company' },
      { name: 'Local Zero Waste Group', type: 'individual' },
    ],
  },
];

// Mock image URLs that load reliably in React Native (picsum.photos)
const MOCK_IMG = (seed: string, w = 400, h = 300) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'submission_1',
    user_id: 'user_2',
    campaign_id: 'campaign_1',
    checkpoint_id: 'checkpoint_1',
    gesture_photo_url: MOCK_IMG('gesture1'),
    before_photo_url: MOCK_IMG('before1'),
    after_photo_url: MOCK_IMG('after1'),
    gps_lat: 7.8136,
    gps_lng: 98.3006,
    before_timestamp: '2025-01-28T10:00:00Z',
    after_timestamp: '2025-01-28T10:05:00Z',
    status: 'pending',
    votes: [
      {
        id: 'validation_1',
        submission_id: 'submission_1',
        validator_id: 'user_3',
        vote: 'approve',
        created_at: '2025-01-28T10:10:00Z',
      },
    ],
    created_at: '2025-01-28T10:05:00Z',
  },
  {
    id: 'submission_1b',
    user_id: 'user_5',
    campaign_id: 'campaign_1',
    checkpoint_id: 'checkpoint_1',
    gesture_photo_url: MOCK_IMG('gesture2'),
    before_photo_url: MOCK_IMG('before2'),
    after_photo_url: MOCK_IMG('after2'),
    gps_lat: 7.8140,
    gps_lng: 98.3010,
    before_timestamp: '2025-01-28T11:00:00Z',
    after_timestamp: '2025-01-28T11:06:00Z',
    status: 'pending',
    votes: [],
    created_at: '2025-01-28T11:06:00Z',
  },
  {
    id: 'submission_2',
    user_id: 'user_4',
    campaign_id: 'campaign_1',
    checkpoint_id: 'checkpoint_1',
    gesture_photo_url: MOCK_IMG('gesture3'),
    before_photo_url: MOCK_IMG('before3'),
    after_photo_url: MOCK_IMG('after3'),
    gps_lat: 7.8136,
    gps_lng: 98.3006,
    before_timestamp: '2025-01-28T09:00:00Z',
    after_timestamp: '2025-01-28T09:08:00Z',
    status: 'approved',
    votes: [
      {
        id: 'validation_2',
        submission_id: 'submission_2',
        validator_id: 'user_3',
        vote: 'approve',
        is_correct: true,
        created_at: '2025-01-28T09:10:00Z',
      },
      {
        id: 'validation_3',
        submission_id: 'submission_2',
        validator_id: 'user_5',
        vote: 'approve',
        is_correct: true,
        created_at: '2025-01-28T09:11:00Z',
      },
      {
        id: 'validation_4',
        submission_id: 'submission_2',
        validator_id: 'user_6',
        vote: 'approve',
        is_correct: true,
        created_at: '2025-01-28T09:12:00Z',
      },
    ],
    created_at: '2025-01-28T09:08:00Z',
  },
  {
    id: 'submission_3',
    user_id: MOCK_USER.id,
    campaign_id: 'campaign_1',
    checkpoint_id: 'checkpoint_1',
    gesture_photo_url: MOCK_IMG('gesture4'),
    before_photo_url: MOCK_IMG('before4'),
    after_photo_url: MOCK_IMG('after4'),
    gps_lat: 7.8136,
    gps_lng: 98.3006,
    before_timestamp: '2025-01-27T14:00:00Z',
    after_timestamp: '2025-01-27T14:07:00Z',
    status: 'approved',
    votes: [
      {
        id: 'validation_5',
        submission_id: 'submission_3',
        validator_id: 'user_3',
        vote: 'approve',
        is_correct: true,
        created_at: '2025-01-27T14:10:00Z',
      },
      {
        id: 'validation_6',
        submission_id: 'submission_3',
        validator_id: 'user_5',
        vote: 'approve',
        is_correct: true,
        created_at: '2025-01-27T14:11:00Z',
      },
      {
        id: 'validation_7',
        submission_id: 'submission_3',
        validator_id: 'user_6',
        vote: 'approve',
        is_correct: true,
        created_at: '2025-01-27T14:12:00Z',
      },
    ],
    created_at: '2025-01-27T14:07:00Z',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { user_id: 'user_7', email: 'champion@example.com', wallet_address: '0x1111...', tickets: 156, rank: 1 },
  { user_id: 'user_8', email: 'runner@example.com', wallet_address: '0x2222...', tickets: 134, rank: 2 },
  { user_id: 'user_9', email: 'third@example.com', wallet_address: '0x3333...', tickets: 98, rank: 3 },
  { user_id: 'user_10', email: 'fourth@example.com', wallet_address: '0x4444...', tickets: 87, rank: 4 },
  { user_id: 'user_11', email: 'fifth@example.com', wallet_address: '0x5555...', tickets: 76, rank: 5 },
  { user_id: MOCK_USER.id, email: MOCK_USER.email, wallet_address: MOCK_USER.wallet_address, tickets: MOCK_USER.tickets, rank: 7 },
  ...Array.from({ length: 15 }, (_, i) => ({
    user_id: `user_${i + 12}`,
    email: `user${i + 12}@example.com`,
    wallet_address: `0x${(i + 12).toString(16).padStart(8, '0')}...`,
    tickets: 50 - i * 2,
    rank: i + 8,
  })),
];

export const MOCK_LOTTERY: Lottery = {
  campaign_id: 'campaign_1',
  status: 'pending',
  draw_date: '2025-02-15T18:00:00Z',
  prize_tiers: [
    { name: 'Grand Prize', amount: 500, count: 1 },
    { name: 'Major Prize', amount: 100, count: 5 },
    { name: 'Minor Prize', amount: 20, count: 20 },
  ],
};

export const MOCK_LOTTERY_COMPLETED: Lottery = {
  campaign_id: 'campaign_1',
  status: 'completed',
  draw_date: '2025-01-25T18:00:00Z',
  winners: [
    { user_id: 'user_7', email: 'champion@example.com', wallet_address: '0x1111...', prize_amount: 500, tier: 'Grand Prize' },
    { user_id: 'user_8', email: 'runner@example.com', wallet_address: '0x2222...', prize_amount: 100, tier: 'Major Prize' },
    { user_id: 'user_9', email: 'third@example.com', wallet_address: '0x3333...', prize_amount: 100, tier: 'Major Prize' },
  ],
  prize_tiers: [
    { name: 'Grand Prize', amount: 500, count: 1 },
    { name: 'Major Prize', amount: 100, count: 5 },
    { name: 'Minor Prize', amount: 20, count: 20 },
  ],
};
